[package]
name = "gitoutofhere"
version = "0.1.0"
authors = ["EnderDev <kieran@dothq.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
